Parameters:
  FullRepoName:
    Type: String
    Description: Example "aws-amplify/amplify-flutter"
    AllowedPattern: ^[a-zA-Z0-9-\_\.]+\/[a-zA-Z0-9-\_\.]+$
    ConstraintDescription: must contain two alphanumeric strings with dashes, periods, or underscores separated by a slash
  AmplifyEnvName:
    Type: String
    Description: Name of Amplify environment for which pull permissions are granted. E.g. "test"
    Default: test
  AmplifyAppName:
    Type: String
    Description: Optional. If provided, pull permissions limited to this app. Otherwise, permissions granted for all apps. Should be all lowercase.

Conditions:
  AllAmplifyApps: !Equals [!Ref AmplifyAppName, ""]
    
Resources:
  IntegrationTestSecrets:
    Type: AWS::SecretsManager::Secret
    Properties:
      # "Amplify Flutter Secrets," abbreviated because it becomes part of
      # environmental variable names.
      Name: afs
      Description: Secrets needed to run integration tests for amplify-flutter
  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: pull_amplify_integration_test_configs
      Policies:
        - PolicyName: AmplifyPullIntegrationTestsS3
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource: !If [AllAmplifyApps, !Sub "arn:aws:s3:::amplify-*${AmplifyEnvName}*", !Sub "arn:aws:s3:::amplify-${AmplifyAppName}-${AmplifyEnvName}*"]
        - PolicyName: AmplifyPullIntegrationTestsCloudformation
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - cloudformation:ListStackResources
                Resource: !If [AllAmplifyApps, !Sub "arn:aws:cloudformation:*amplify*${AmplifyEnvName}*", !Sub "arn:aws:cloudformation:*amplify-${AmplifyAppName}-${AmplifyEnvName}*"]
        - PolicyName: AmplifyPullIntegrationTestsAmplify
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - amplify:GetApp
                  - amplify:GetBackendEnvironment
                Resource: "arn:aws:amplify:*"
        # Secrets manager permissions as documented on https://github.com/marketplace/actions/aws-secrets-manager-github-action.
        - PolicyName: ListIntegrationTestSecrets
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action: secretsmanager:ListSecrets
                Resource: !Ref IntegrationTestSecrets
        - PolicyName: GetIntegrationTestSecrets
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action: secretsmanager:GetSecretValue
                Resource: !Ref IntegrationTestSecrets
        - PolicyName: PutMetricData
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action: cloudwatch:PutMetricData
                Resource: '*'
                Condition:
                  ForAllValues:StringEqualsIgnoreCase:
                    cloudwatch:namespace:
                      - GithubCanaryApps
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated: !Ref GithubOidc
            Condition:
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:${FullRepoName}:*

  GithubOidc:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ThumbprintList: 
        - 6938fd4d98bab03faadb97b34396831e3780aea1
        - 1c58a3a8518e8759bf075b76b750d4f2df264fcd
      ClientIdList: 
        - sts.amazonaws.com

Outputs:
  Role:
    Value: !GetAtt Role.Arn
