version: 0.2
env:
  shell: /bin/sh
phases:
  install:
    commands:
      - echo 'Install phase starting'
      - npm install -g @aws-amplify/cli
    finally:
      - echo 'Install phase completed.'
  pre_build:
    commands:
      - echo 'Pre-build phase starting'
    finally:
      - echo 'Pre-build phase completed.'
  build:
    commands:
      - echo 'Build phase starting'
      - pwd
      - ls -al
      - src/integ_test_resources/android/amplify/integration/cdk/scripts/setup_auth
    finally:
      - echo 'Build phase completed.'
  post_build:
    commands:
      - echo 'Post-build phase starting'
    finally:
      - echo 'Post-build phase completed.'
