#!/usr/bin/env python3
import os
from common import *
from auth import *
from api import *
from storage import *

# ENTRY POINT
os.system(f"mkdir -p {PROJECT_DIR}")

existing_app = get_existing_app_id()
if existing_app is None:
    # create the app
    print("Need to create a new app")
    initialize_new_app()
else:
    # pull the app
    print(f"Pulling existing app with id {existing_app['appId']}")
    pull_existing_app(existing_app['appId'])

code = config_storage()
push()
'''
#auth_config = get_auth_config()
#if config_auth(auth_config) == 0:

    #api_config = get_api_config('AmplifyAndroidIntegTestApi', f"{SCRIPTS_DIR}/../schemas", "authAndroidIntegTestAuth")
    #config_api(api_config)
    
    #create_users()
#else:
#    print("Failed to configure auth.")
'''